spring:
  application:
    name: product-service

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/product-service?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
